// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIACU-Qb-p0NNvKsOp9VbUh4X6DIIev0',
    appId: '1:719835614351:web:6237cc25902092aeb734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    authDomain: 'shakshak-app.firebaseapp.com',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-RfTOghAenGmR-FzACYbqKrWwrSirJKI',
    appId: '1:719835614351:android:03c8441e11e5f842b734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwm_gmx7nFw8T4aEBs0axQCSTrnnxH4M',
    appId: '1:719835614351:ios:a8d77785afb0a426b734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
    iosClientId: '719835614351-m8kirdlpbe11jkm5do9tjthbli4dp27t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpwm_gmx7nFw8T4aEBs0axQCSTrnnxH4M',
    appId: '1:719835614351:ios:a8d77785afb0a426b734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
    iosClientId: '719835614351-m8kirdlpbe11jkm5do9tjthbli4dp27t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClIACU-Qb-p0NNvKsOp9VbUh4X6DIIev0',
    appId: '1:719835614351:web:cc608b4de2572e63b734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    authDomain: 'shakshak-app.firebaseapp.com',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );
}
