
// File generated by FlutterFire CLI. DO NOT MODIFY.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIACU-Qb-p0NNvKsOp9VbUh4X6DIIev0',
    appId: '1:719835614351:web:6237cc25902092aeb734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    authDomain: 'shakshak-app.firebaseapp.com',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-RfTOghAenGmR-FzACYbqKrWwrSirJKI',
    appId: '1:719835614351:android:03c8441e11e5f842b734fa',
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your iOS API key
    appId: 'YOUR_APP_ID', // Replace with your iOS App ID
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Replace with your iOS Client ID
    iosBundleId: 'YOUR_IOS_BUNDLE_ID', // Replace with your iOS Bundle ID
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

    static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your macOS API key
    appId: 'YOUR_APP_ID', // Replace with your macOS App ID
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your Windows API key
    appId: 'YOUR_APP_ID', // Replace with your Windows App ID
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your Linux API key
    appId: 'YOUR_APP_ID', // Replace with your Linux App ID
    messagingSenderId: '719835614351',
    projectId: 'shakshak-app',
    storageBucket: 'shakshak-app.firebasestorage.app',
  );
}